[default]

    [default.ICA]

    PILAR = "ESG"
    TEMA = "ESG"
    KPI = "CONSUMO DE AGUA"
    INDICADOR = "ICA"

        [default.ICA.MODEL]

        MODEL = "INDICE"
        PONTO_A = [1.0, 9.0]
        PONTO_B = [1.3, 7.0]

    [default.TCX]

    PILAR = "PERFORMANCE"
    TEMA = "AB"
    KPI = "DISPONIBILIDADE TCX"
    INDICADOR = "REINICIALIZAÇÕES"

        [default.TCX.MODEL]

        MODEL = "INFLEXAO"
        PONTO_A = [2.0, 7.0]
        PONTO_B = [0.0, 10.0]

[development]